volumes:
  postgres_data:
  go_mods:
  go_tools:

services:
  postgres:
    # Azure Database for PostgreSQL latest supported version
    # https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-supported-versions
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/dump.sql:/docker-entrypoint-initdb.d/init.sql
  go-backend:
    image: golang:1.25
    container_name: saas-backend
    restart: unless-stopped
    ports:
      - "8008:8008"
    environment:
      SERVER_PORT: "8008"
      DATABASE_NAME: "database"
      DATABASE_URL: "postgresql://postgres:postgres@host.docker.internal:5432/database?sslmode=disable"
      APP_BASE_URL: "http://localhost:8009/"
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/app
      - go_mods:/go/pkg/mod
      - go_tools:/go/bin
    working_dir: /app
    entrypoint:
      - /bin/sh
      - -c
      - |
        # Install Air if not already installed
        if ! command -v air &> /dev/null; then
          echo "Installing Air..."
          go install github.com/air-verse/air@latest
        fi
        # Run worker in background
        ./commands.sh worker &
        # Run webserver with Air for hot reloading
        /go/bin/air -c .air.toml
    profiles:
      - saas-backend
