/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * SaaS Template Admin API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './axios-v1-admin';
import type { ErrorType } from './axios-v1-admin';
export interface MessageResponse {
  message?: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Admin health check
 */
export const getGetApiAdminV1HealthUrl = () => {


  

  return `/health`
}

export const getApiAdminV1Health = async ( options?: RequestInit): Promise<MessageResponse> => {
  
  return customInstance<MessageResponse>(getGetApiAdminV1HealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetApiAdminV1HealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const getGetApiAdminV1HealthQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminV1Health>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminV1Health>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminV1HealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminV1Health>>> = ({ signal }) => getApiAdminV1Health({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminV1Health>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminV1HealthQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminV1Health>>>
export type GetApiAdminV1HealthQueryError = ErrorType<unknown>


export function useGetApiAdminV1Health<TData = Awaited<ReturnType<typeof getApiAdminV1Health>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminV1Health>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminV1Health>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminV1Health>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminV1Health<TData = Awaited<ReturnType<typeof getApiAdminV1Health>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminV1Health>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminV1Health>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminV1Health>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminV1Health<TData = Awaited<ReturnType<typeof getApiAdminV1Health>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminV1Health>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Admin health check
 */

export function useGetApiAdminV1Health<TData = Awaited<ReturnType<typeof getApiAdminV1Health>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminV1Health>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminV1HealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
