/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Go Backend Public API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './axios-v1-public';
import type { ErrorType , BodyType } from './axios-v1-public';
export interface Error {
  message?: string;
}

export type PostApiV1SigninBody = {
  email: string;
  password: string;
};

export type PostApiV1SignupBody = {
  email: string;
  /** @minLength 8 */
  password: string;
  confirm_password: string;
  first_name?: string;
  last_name?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Returns a health check response
 */
export type getApiV1HealthResponse200 = {
  data: string
  status: 200
}

export type getApiV1HealthResponseSuccess = (getApiV1HealthResponse200) & {
  headers: Headers;
};
;

export type getApiV1HealthResponse = (getApiV1HealthResponseSuccess)

export const getGetApiV1HealthUrl = () => {


  

  return `/health`
}

export const getApiV1Health = async ( options?: RequestInit): Promise<getApiV1HealthResponse> => {
  
  return customInstance<getApiV1HealthResponse>(getGetApiV1HealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetApiV1HealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const getGetApiV1HealthQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1HealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Health>>> = ({ signal }) => getApiV1Health({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1HealthQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Health>>>
export type GetApiV1HealthQueryError = ErrorType<unknown>


export function useGetApiV1Health<TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Health>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Health>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Health<TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Health>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Health>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Health<TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns a health check response
 */

export function useGetApiV1Health<TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1HealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Logs in a user and returns a session cookie
 */
export type postApiV1SigninResponse200 = {
  data: string
  status: 200
}

export type postApiV1SigninResponse401 = {
  data: Error
  status: 401
}

export type postApiV1SigninResponseSuccess = (postApiV1SigninResponse200) & {
  headers: Headers;
};
export type postApiV1SigninResponseError = (postApiV1SigninResponse401) & {
  headers: Headers;
};

export type postApiV1SigninResponse = (postApiV1SigninResponseSuccess | postApiV1SigninResponseError)

export const getPostApiV1SigninUrl = () => {


  

  return `/signin`
}

export const postApiV1Signin = async (postApiV1SigninBody: PostApiV1SigninBody, options?: RequestInit): Promise<postApiV1SigninResponse> => {
  
  return customInstance<postApiV1SigninResponse>(getPostApiV1SigninUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SigninBody,)
  }
);}
  



export const getPostApiV1SigninMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signin>>, TError,{data: BodyType<PostApiV1SigninBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signin>>, TError,{data: BodyType<PostApiV1SigninBody>}, TContext> => {

const mutationKey = ['postApiV1Signin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Signin>>, {data: BodyType<PostApiV1SigninBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Signin(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SigninMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Signin>>>
    export type PostApiV1SigninMutationBody = BodyType<PostApiV1SigninBody>
    export type PostApiV1SigninMutationError = ErrorType<Error>

    /**
 * @summary Logs in a user and returns a session cookie
 */
export const usePostApiV1Signin = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signin>>, TError,{data: BodyType<PostApiV1SigninBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Signin>>,
        TError,
        {data: BodyType<PostApiV1SigninBody>},
        TContext
      > => {
      return useMutation(getPostApiV1SigninMutationOptions(options), queryClient);
    }
    
/**
 * @summary Sign up a new user
 */
export type postApiV1SignupResponse200 = {
  data: string
  status: 200
}

export type postApiV1SignupResponse400 = {
  data: Error
  status: 400
}

export type postApiV1SignupResponseSuccess = (postApiV1SignupResponse200) & {
  headers: Headers;
};
export type postApiV1SignupResponseError = (postApiV1SignupResponse400) & {
  headers: Headers;
};

export type postApiV1SignupResponse = (postApiV1SignupResponseSuccess | postApiV1SignupResponseError)

export const getPostApiV1SignupUrl = () => {


  

  return `/signup`
}

export const postApiV1Signup = async (postApiV1SignupBody: PostApiV1SignupBody, options?: RequestInit): Promise<postApiV1SignupResponse> => {
  
  return customInstance<postApiV1SignupResponse>(getPostApiV1SignupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SignupBody,)
  }
);}
  



export const getPostApiV1SignupMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signup>>, TError,{data: BodyType<PostApiV1SignupBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signup>>, TError,{data: BodyType<PostApiV1SignupBody>}, TContext> => {

const mutationKey = ['postApiV1Signup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Signup>>, {data: BodyType<PostApiV1SignupBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Signup(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SignupMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Signup>>>
    export type PostApiV1SignupMutationBody = BodyType<PostApiV1SignupBody>
    export type PostApiV1SignupMutationError = ErrorType<Error>

    /**
 * @summary Sign up a new user
 */
export const usePostApiV1Signup = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signup>>, TError,{data: BodyType<PostApiV1SignupBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Signup>>,
        TError,
        {data: BodyType<PostApiV1SignupBody>},
        TContext
      > => {
      return useMutation(getPostApiV1SignupMutationOptions(options), queryClient);
    }
    
/**
 * @summary Signs out the current user by clearing the session
 */
export type postApiV1SignoutResponse200 = {
  data: string
  status: 200
}

export type postApiV1SignoutResponseSuccess = (postApiV1SignoutResponse200) & {
  headers: Headers;
};
;

export type postApiV1SignoutResponse = (postApiV1SignoutResponseSuccess)

export const getPostApiV1SignoutUrl = () => {


  

  return `/signout`
}

export const postApiV1Signout = async ( options?: RequestInit): Promise<postApiV1SignoutResponse> => {
  
  return customInstance<postApiV1SignoutResponse>(getPostApiV1SignoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  



export const getPostApiV1SignoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signout>>, TError,void, TContext> => {

const mutationKey = ['postApiV1Signout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Signout>>, void> = () => {
          

          return  postApiV1Signout(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SignoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Signout>>>
    
    export type PostApiV1SignoutMutationError = ErrorType<unknown>

    /**
 * @summary Signs out the current user by clearing the session
 */
export const usePostApiV1Signout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Signout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1SignoutMutationOptions(options), queryClient);
    }
