/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * SaaS Template Public API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { customInstance } from './axios-v1-public';
import type { ErrorType , BodyType } from './axios-v1-public';
export interface Error {
  message?: string;
}

export interface MessageResponse {
  message?: string;
}

export type ValidationErrorData = {
  errors?: string[];
};

export interface ValidationError {
  message?: string;
  data?: ValidationErrorData;
}

export type PostApiV1SigninBody = {
  email: string;
  password: string;
};

export type PostApiV1SignupBody = {
  email: string;
  /** @minLength 8 */
  password: string;
  confirm_password: string;
  first_name?: string;
  last_name?: string;
};

export type PostApiV1ForgotPasswordBody = {
  email: string;
};

export type PostApiV1ResetPasswordBody = {
  token: string;
  /** @minLength 8 */
  password: string;
  confirm_password: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Logs in a user and returns a session cookie
 */
export const getPostApiV1SigninUrl = () => {


  

  return `/signin`
}

export const postApiV1Signin = async (postApiV1SigninBody: PostApiV1SigninBody, options?: RequestInit): Promise<MessageResponse> => {
  
  return customInstance<MessageResponse>(getPostApiV1SigninUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SigninBody,)
  }
);}
  



export const getPostApiV1SigninMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signin>>, TError,{data: BodyType<PostApiV1SigninBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signin>>, TError,{data: BodyType<PostApiV1SigninBody>}, TContext> => {

const mutationKey = ['postApiV1Signin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Signin>>, {data: BodyType<PostApiV1SigninBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Signin(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SigninMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Signin>>>
    export type PostApiV1SigninMutationBody = BodyType<PostApiV1SigninBody>
    export type PostApiV1SigninMutationError = ErrorType<Error>

    /**
 * @summary Logs in a user and returns a session cookie
 */
export const usePostApiV1Signin = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signin>>, TError,{data: BodyType<PostApiV1SigninBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Signin>>,
        TError,
        {data: BodyType<PostApiV1SigninBody>},
        TContext
      > => {
      return useMutation(getPostApiV1SigninMutationOptions(options), queryClient);
    }
    
/**
 * @summary Sign up a new user
 */
export const getPostApiV1SignupUrl = () => {


  

  return `/signup`
}

export const postApiV1Signup = async (postApiV1SignupBody: PostApiV1SignupBody, options?: RequestInit): Promise<MessageResponse> => {
  
  return customInstance<MessageResponse>(getPostApiV1SignupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SignupBody,)
  }
);}
  



export const getPostApiV1SignupMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signup>>, TError,{data: BodyType<PostApiV1SignupBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signup>>, TError,{data: BodyType<PostApiV1SignupBody>}, TContext> => {

const mutationKey = ['postApiV1Signup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Signup>>, {data: BodyType<PostApiV1SignupBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Signup(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SignupMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Signup>>>
    export type PostApiV1SignupMutationBody = BodyType<PostApiV1SignupBody>
    export type PostApiV1SignupMutationError = ErrorType<Error>

    /**
 * @summary Sign up a new user
 */
export const usePostApiV1Signup = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signup>>, TError,{data: BodyType<PostApiV1SignupBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Signup>>,
        TError,
        {data: BodyType<PostApiV1SignupBody>},
        TContext
      > => {
      return useMutation(getPostApiV1SignupMutationOptions(options), queryClient);
    }
    
/**
 * @summary Signs out the current user by clearing the session
 */
export const getPostApiV1SignoutUrl = () => {


  

  return `/signout`
}

export const postApiV1Signout = async ( options?: RequestInit): Promise<MessageResponse> => {
  
  return customInstance<MessageResponse>(getPostApiV1SignoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  



export const getPostApiV1SignoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signout>>, TError,void, TContext> => {

const mutationKey = ['postApiV1Signout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Signout>>, void> = () => {
          

          return  postApiV1Signout(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SignoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Signout>>>
    
    export type PostApiV1SignoutMutationError = ErrorType<unknown>

    /**
 * @summary Signs out the current user by clearing the session
 */
export const usePostApiV1Signout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Signout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Signout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1SignoutMutationOptions(options), queryClient);
    }
    
/**
 * @summary Request a password reset email
 */
export const getPostApiV1ForgotPasswordUrl = () => {


  

  return `/forgot-password`
}

export const postApiV1ForgotPassword = async (postApiV1ForgotPasswordBody: PostApiV1ForgotPasswordBody, options?: RequestInit): Promise<MessageResponse> => {
  
  return customInstance<MessageResponse>(getPostApiV1ForgotPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1ForgotPasswordBody,)
  }
);}
  



export const getPostApiV1ForgotPasswordMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ForgotPassword>>, TError,{data: BodyType<PostApiV1ForgotPasswordBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ForgotPassword>>, TError,{data: BodyType<PostApiV1ForgotPasswordBody>}, TContext> => {

const mutationKey = ['postApiV1ForgotPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ForgotPassword>>, {data: BodyType<PostApiV1ForgotPasswordBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1ForgotPassword(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ForgotPassword>>>
    export type PostApiV1ForgotPasswordMutationBody = BodyType<PostApiV1ForgotPasswordBody>
    export type PostApiV1ForgotPasswordMutationError = ErrorType<unknown>

    /**
 * @summary Request a password reset email
 */
export const usePostApiV1ForgotPassword = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ForgotPassword>>, TError,{data: BodyType<PostApiV1ForgotPasswordBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ForgotPassword>>,
        TError,
        {data: BodyType<PostApiV1ForgotPasswordBody>},
        TContext
      > => {
      return useMutation(getPostApiV1ForgotPasswordMutationOptions(options), queryClient);
    }
    
/**
 * @summary Reset password using a token
 */
export const getPostApiV1ResetPasswordUrl = () => {


  

  return `/reset-password`
}

export const postApiV1ResetPassword = async (postApiV1ResetPasswordBody: PostApiV1ResetPasswordBody, options?: RequestInit): Promise<MessageResponse> => {
  
  return customInstance<MessageResponse>(getPostApiV1ResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1ResetPasswordBody,)
  }
);}
  



export const getPostApiV1ResetPasswordMutationOptions = <TError = ErrorType<ValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ResetPassword>>, TError,{data: BodyType<PostApiV1ResetPasswordBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ResetPassword>>, TError,{data: BodyType<PostApiV1ResetPasswordBody>}, TContext> => {

const mutationKey = ['postApiV1ResetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ResetPassword>>, {data: BodyType<PostApiV1ResetPasswordBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1ResetPassword(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ResetPassword>>>
    export type PostApiV1ResetPasswordMutationBody = BodyType<PostApiV1ResetPasswordBody>
    export type PostApiV1ResetPasswordMutationError = ErrorType<ValidationError>

    /**
 * @summary Reset password using a token
 */
export const usePostApiV1ResetPassword = <TError = ErrorType<ValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ResetPassword>>, TError,{data: BodyType<PostApiV1ResetPasswordBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ResetPassword>>,
        TError,
        {data: BodyType<PostApiV1ResetPasswordBody>},
        TContext
      > => {
      return useMutation(getPostApiV1ResetPasswordMutationOptions(options), queryClient);
    }
