/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * SaaS Template API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './axios-v1';
import type { ErrorType , BodyType } from './axios-v1';
export interface Error {
  message?: string;
}

export type BaseUserRole = typeof BaseUserRole[keyof typeof BaseUserRole];


export const BaseUserRole = {
  admin: 'admin',
  user: 'user',
} as const;

/**
 * Base user detail
 */
export interface BaseUser {
  email: string;
  id: string;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  role: BaseUserRole;
  onboardingCompleted: boolean;
}

export interface UpdateOnboardingRequest {
  onboardingCompleted: boolean;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Return authenticated user
 */
export const getGetApiV1UserUrl = () => {


  

  return `/user`
}

export const getApiV1User = async ( options?: RequestInit): Promise<BaseUser> => {
  
  return customInstance<BaseUser>(getGetApiV1UserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetApiV1UserQueryKey = () => {
    return [
    `/user`
    ] as const;
    }

    
export const getGetApiV1UserQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1User>>, TError = ErrorType<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1UserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1User>>> = ({ signal }) => getApiV1User({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1UserQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1User>>>
export type GetApiV1UserQueryError = ErrorType<Error>


export function useGetApiV1User<TData = Awaited<ReturnType<typeof getApiV1User>>, TError = ErrorType<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1User>>,
          TError,
          Awaited<ReturnType<typeof getApiV1User>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1User<TData = Awaited<ReturnType<typeof getApiV1User>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1User>>,
          TError,
          Awaited<ReturnType<typeof getApiV1User>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1User<TData = Awaited<ReturnType<typeof getApiV1User>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Return authenticated user
 */

export function useGetApiV1User<TData = Awaited<ReturnType<typeof getApiV1User>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1UserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Update user onboarding preferences
 */
export const getPatchApiV1UserOnboardingUrl = () => {


  

  return `/user/onboarding`
}

export const patchApiV1UserOnboarding = async (updateOnboardingRequest: UpdateOnboardingRequest, options?: RequestInit): Promise<BaseUser> => {
  
  return customInstance<BaseUser>(getPatchApiV1UserOnboardingUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOnboardingRequest,)
  }
);}
  



export const getPatchApiV1UserOnboardingMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1UserOnboarding>>, TError,{data: BodyType<UpdateOnboardingRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1UserOnboarding>>, TError,{data: BodyType<UpdateOnboardingRequest>}, TContext> => {

const mutationKey = ['patchApiV1UserOnboarding'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1UserOnboarding>>, {data: BodyType<UpdateOnboardingRequest>}> = (props) => {
          const {data} = props ?? {};

          return  patchApiV1UserOnboarding(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1UserOnboardingMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1UserOnboarding>>>
    export type PatchApiV1UserOnboardingMutationBody = BodyType<UpdateOnboardingRequest>
    export type PatchApiV1UserOnboardingMutationError = ErrorType<void>

    /**
 * @summary Update user onboarding preferences
 */
export const usePatchApiV1UserOnboarding = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1UserOnboarding>>, TError,{data: BodyType<UpdateOnboardingRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1UserOnboarding>>,
        TError,
        {data: BodyType<UpdateOnboardingRequest>},
        TContext
      > => {
      return useMutation(getPatchApiV1UserOnboardingMutationOptions(options), queryClient);
    }
