/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Adobo API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './axios-v1';
import type { ErrorType } from './axios-v1';
export interface Error {
  message?: string;
}

/**
 * Base user detail
 */
export interface BaseUser {
  email: string;
  id: string;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Return authenticated user
 */
export type getApiV1UserResponse200 = {
  data: BaseUser
  status: 200
}

export type getApiV1UserResponse401 = {
  data: Error
  status: 401
}

export type getApiV1UserResponseSuccess = (getApiV1UserResponse200) & {
  headers: Headers;
};
export type getApiV1UserResponseError = (getApiV1UserResponse401) & {
  headers: Headers;
};

export type getApiV1UserResponse = (getApiV1UserResponseSuccess | getApiV1UserResponseError)

export const getGetApiV1UserUrl = () => {


  

  return `/user`
}

export const getApiV1User = async ( options?: RequestInit): Promise<getApiV1UserResponse> => {
  
  return customInstance<getApiV1UserResponse>(getGetApiV1UserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetApiV1UserQueryKey = () => {
    return [
    `/user`
    ] as const;
    }

    
export const getGetApiV1UserQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1User>>, TError = ErrorType<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1UserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1User>>> = ({ signal }) => getApiV1User({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1UserQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1User>>>
export type GetApiV1UserQueryError = ErrorType<Error>


export function useGetApiV1User<TData = Awaited<ReturnType<typeof getApiV1User>>, TError = ErrorType<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1User>>,
          TError,
          Awaited<ReturnType<typeof getApiV1User>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1User<TData = Awaited<ReturnType<typeof getApiV1User>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1User>>,
          TError,
          Awaited<ReturnType<typeof getApiV1User>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1User<TData = Awaited<ReturnType<typeof getApiV1User>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Return authenticated user
 */

export function useGetApiV1User<TData = Awaited<ReturnType<typeof getApiV1User>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1User>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1UserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
